'use client';

import React, { useState, useEffect } from 'react';
import ReusableNode from '../../components/ReusableNode';
import ReusableGrid from '../../components/ReusableGrid';

interface GenerationResult {
  metadata: {
    generatedAt: string;
    totalRequests: number;
    successful: number;
    failed: number;
    agentTypes: string[];
    processingTimeMs: number;
  };
  sentences: Record<string, any>;
  charts: Array<{
    id: string;
    name: string;
    request: any;
    chartSpec: any;
    vegaSpec: any;
    generationTime: number;
    success: boolean;
    error: string | null;
  }>;
  systemInfo?: {
    availableAgents: Array<{
      type: string;
      info: any;
    }>;
  };
}

interface ScenarioFile {
  name: string;
  path: string;
  scenario: string;
}

const ChartGenerator: React.FC = () => {
  const [availableFiles, setAvailableFiles] = useState<ScenarioFile[]>([]);
  const [selectedFile, setSelectedFile] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStatus, setGenerationStatus] = useState<string>('');
  const [generationResult, setGenerationResult] = useState<GenerationResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selectedSentence, setSelectedSentence] = useState<string>('1'); // Default to first sentence

  useEffect(() => {
    loadAvailableFiles();
  }, []);

  // Auto-select first sentence when generation result changes
  useEffect(() => {
    if (generationResult?.sentences) {
      const firstSentenceId = Object.keys(generationResult.sentences)[0];
      if (firstSentenceId) {
        setSelectedSentence(firstSentenceId);
      }
    }
  }, [generationResult]);

  const loadAvailableFiles = async () => {
    try {
      const response = await fetch('/api/list-scenario-files');
      if (response.ok) {
        const files = await response.json();
        setAvailableFiles(files);
      } else {
        throw new Error('Failed to load scenario files');
      }
    } catch (error) {
      console.error('Error loading files:', error);
      // Fallback to known files
      setAvailableFiles([
        { name: 'test.json', path: 'public/examples/scenario1/test.json', scenario: 'scenario1' },
        { name: 'example4_data.json', path: 'public/examples/scenario1/example4_data.json', scenario: 'scenario1' },
        { name: 'example4_data.json', path: 'public/examples/scenario2/example4_data.json', scenario: 'scenario2' }
      ]);
    }
  };

  const generateCharts = async () => {
    if (!selectedFile) return;

    setIsGenerating(true);
    setGenerationStatus('Initializing travel agent system...');
    setError(null);
    setGenerationResult(null);

    try {
      const response = await fetch('/api/generate-charts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          inputFile: selectedFile
        })
      });

      if (!response.ok) {
        throw new Error(`Generation failed: ${response.statusText}`);
      }

      const result = await response.json();
      
      if (result.success) {
        setGenerationResult(result.data);
        setGenerationStatus(`✅ Generated ${result.data.metadata.successful}/${result.data.metadata.totalRequests} charts successfully!`);
      } else {
        throw new Error(result.error);
      }

    } catch (error) {
      setError(error instanceof Error ? error.message : 'Unknown error');
      setGenerationStatus('❌ Generation failed');
    } finally {
      setIsGenerating(false);
    }
  };

  const resetGenerator = () => {
    setGenerationResult(null);
    setError(null);
    setGenerationStatus('');
    setSelectedFile('');
    setSelectedSentence('1');
  };

  if (isGenerating) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center max-w-md mx-auto p-6">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <h2 className="text-xl font-semibold text-gray-700 mb-4">Generating Charts with Real AI Agents</h2>
          <p className="text-gray-600 mb-4">{generationStatus}</p>
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 text-left">
            <p className="text-sm text-blue-700">
              <strong>Processing:</strong> Each chart is being generated by specialized agents:
            </p>
            <ul className="text-xs text-blue-600 mt-2 space-y-1">
              <li>• Map charts → Direct map generation</li>
              <li>• Bar charts → HorizontalBarAgent, DivergingBarAgent</li>
              <li>• Pie charts → PieChartAgent + filter variations</li>
              <li>• Scatter plots → ScatterChartAgent</li>
              <li>• Line charts → LineChartAgent</li>
              <li>• Multi-type → MultiTypeChartAgent</li>
            </ul>
          </div>
        </div>
      </div>
    );
  }

  if (generationResult) {
    // Extract sentences for separate dashboards
    const sentences = generationResult.sentences || {};
    const sentenceIds = Object.keys(sentences);

    return (
      <div className="min-h-screen bg-gray-50">
        {/* Header */}
        <div className="bg-white border-b border-gray-200 px-6 py-4">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Chart Generation Results</h1>
              <p className="text-sm text-gray-600">
                Generated {generationResult.metadata.successful}/{generationResult.metadata.totalRequests} charts from {selectedFile} • 
                {' '}Processing time: {(generationResult.metadata.processingTimeMs / 1000).toFixed(1)}s •
                {' '}{sentenceIds.length} dashboard{sentenceIds.length !== 1 ? 's' : ''}
              </p>
            </div>
            <button
              onClick={resetGenerator}
              className="bg-gray-100 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-200 transition-colors font-medium text-sm"
            >
              🔄 Generate New Charts
            </button>
          </div>
        </div>

        {/* Dashboard Tabs */}
        <div className="bg-white border-b border-gray-200">
          <div className="flex space-x-1 px-6">
            {sentenceIds.map((sentenceId) => (
              <button
                key={sentenceId}
                onClick={() => setSelectedSentence(sentenceId)}
                className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                  selectedSentence === sentenceId
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700'
                }`}
              >
                Dashboard {sentenceId}
                <span className="ml-1 text-xs bg-gray-100 px-1.5 py-0.5 rounded">
                  {sentences[sentenceId]?.charts?.length || 0}
                </span>
              </button>
            ))}
          </div>
        </div>

        {/* Charts Grid for Selected Sentence */}
        <div className="p-6">
          {selectedSentence && sentences[selectedSentence] ? (
            <>
              <div className="mb-4">
                <h2 className="text-lg font-semibold text-gray-800">
                  Dashboard {selectedSentence}
                </h2>
                <p className="text-sm text-gray-600">
                  {sentences[selectedSentence].charts?.length || 0} charts in this dashboard
                </p>
              </div>
              
              <ReusableGrid config="travel-dashboard" isLoading={false}>
                {(sentences[selectedSentence].charts || []).map((chart: any) => {
                  if (!chart.success) {
                    return (
                      <ReusableNode
                        key={chart.id}
                        size="medium"
                        chartType="custom"
                        title={chart.name}
                        subtitle="Generation Failed"
                        description={`Error: ${chart.error}`}
                        chartPosition="full"
                      >
                        <div className="h-40 flex items-center justify-center">
                          <div className="text-center">
                            <div className="text-4xl mb-2">❌</div>
                            <p className="text-sm text-red-600 font-medium">Generation Failed</p>
                            <p className="text-xs text-gray-500 mt-1 max-w-xs">{chart.error}</p>
                          </div>
                        </div>
                      </ReusableNode>
                    );
                  }

                  const chartType = chart.chartSpec?.type || chart.request?.constraints?.chartType || 'bar';
                  const nodeSize = chart.request?.constraints?.nodeSize || 'xlarge';

                  return (
                    <ReusableNode
                      key={chart.id}
                      size={nodeSize as 'small' | 'medium' | 'large' | 'xlarge'}
                      chartType={chartType === 'map' ? 'vega' : 'vega-lite'}
                      title={chart.name}
                      subtitle={chart.chartSpec?.subtitle || null}
                      description={chart.request?.userQuery}
                      vegaSpec={chart.vegaSpec}
                      chartPosition="full"
                    >
                      <div className="mt-2 text-xs text-gray-500">
                        <p><strong>Agent:</strong> {chart.chartSpec?.metadata?.generatedBy}</p>
                        <p><strong>Generation time:</strong> {chart.generationTime}ms</p>
                      </div>
                    </ReusableNode>
                  );
                })}
              </ReusableGrid>
            </>
          ) : (
            <div className="text-center py-12">
              <div className="text-gray-400 text-lg">Select a dashboard to view charts</div>
            </div>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="text-center max-w-2xl mx-auto p-6">
        <div className="text-6xl mb-4">🎨</div>
        <h1 className="text-3xl font-bold text-gray-900 mb-4">Chart Generator</h1>
        <p className="text-gray-600 mb-8">
          Generate charts from scenario files using real travel agent system with OpenAI API
        </p>

        {error && (
          <div className="bg-red-100 border border-red-200 rounded-lg p-4 mb-6">
            <p className="text-sm text-red-600">{error}</p>
          </div>
        )}

        {/* File Selection */}
        <div className="bg-white border border-gray-200 rounded-lg p-6 mb-6">
          <h3 className="text-lg font-semibold text-gray-800 mb-4">Select Input File</h3>
          
          {availableFiles.length === 0 ? (
            <div className="text-gray-500">Loading available files...</div>
          ) : (
            <div className="space-y-3">
              {availableFiles.map((file) => (
                <label key={file.path} className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="radio"
                    name="selectedFile"
                    value={file.path}
                    checked={selectedFile === file.path}
                    onChange={(e) => setSelectedFile(e.target.value)}
                    className="text-blue-600"
                  />
                  <div className="flex-1 text-left">
                    <div className="font-medium">{file.name}</div>
                    <div className="text-sm text-gray-500">{file.scenario} • {file.path}</div>
                  </div>
                </label>
              ))}
            </div>
          )}
        </div>

        {/* Generate Button */}
        <button
          onClick={generateCharts}
          disabled={!selectedFile || isGenerating}
          className={`px-8 py-4 rounded-lg font-medium text-lg transition-colors ${
            selectedFile && !isGenerating
              ? 'bg-blue-600 text-white hover:bg-blue-700'
              : 'bg-gray-300 text-gray-500 cursor-not-allowed'
          }`}
        >
          {isGenerating ? 'Generating...' : '🚀 Generate Charts with Real AI Agents'}
        </button>

        {selectedFile && (
          <div className="mt-4 text-sm text-gray-600">
            Output will be saved as: <code>{selectedFile.replace('.json', '_output.json')}</code>
          </div>
        )}

        {/* Info Section */}
        <div className="mt-8 p-4 bg-blue-50 border border-blue-200 rounded-lg text-left">
          <h4 className="font-medium text-blue-800 mb-2">How It Works:</h4>
          <div className="text-sm text-blue-700 space-y-1">
            <p>• Reads input files from scenario1/scenario2 folders</p>
            <p>• Uses real TravelAgentManager with specialized agents</p>
            <p>• Each chart type calls its dedicated agent (HorizontalBarAgent, PieChartAgent, etc.)</p>
            <p>• Agents make actual OpenAI API calls to generate contextual data</p>
            <p>• Creates interactive filter variations for supported charts</p>
            <p>• Saves output to *_output.json in the same folder</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ChartGenerator;