#!/usr/bin/env python3
"""
QSF Templates and Batch Question Generator
Specific templates for chart evaluation surveys
"""

from qsf_utils import QSFBuilder
import json
from typing import List, Dict

# Template data for chart evaluation questions
CHART_EVALUATION_TEMPLATE = {
    "choices": [
        "Does the generated chart plan match the intent of the vague prompt?",
        "Does the generated chart plan have the potential to support further exploration?"
    ],
    "scale_labels": ["Strongly Disagree", "Strongly Agree"]
}

def create_vague_prompt_html(prompt: str) -> str:
    """Create styled HTML for vague prompt display"""
    return f"""<div style="font-family: Arial, sans-serif; margin: 24px auto; line-height: 1.6;">

  <div style="background:#fff3cd; border:1px solid #f0c36d; border-radius:12px; padding:24px; margin-bottom:20px; box-shadow:0 2px 6px rgba(0,0,0,0.06); text-align:center;">
    <h2 style="color:#7a5c00; margin:0; font-size:22px;">User's Vague Prompt</h2>
    <p style="margin:10px 0 0; font-size:20px; font-weight:bold; color:#333;">
      "{prompt}"
    </p>
  </div>"""

def create_chart_plans_html(plans: List[Dict[str, str]]) -> str:
    """Create styled HTML for chart plans"""
    plans_html = ""
    for plan in plans:
        plans_html += f"""
    <div style="margin-bottom:16px;">
      <p style="margin:0; font-weight:bold; font-size:16px;">{plan['title']}</p>
      <p style="margin:2px 0; color:#555;"><i>{plan['type']}</i></p>
      <p style="margin:4px 0;">{plan['description']}</p>
    </div>"""
    
    return f"""
  <div style="background:#ffffff; border:1px solid #e5e7eb; border-radius:10px; padding:20px; margin-bottom:24px;">
    <h3 style="color:#0f6cab; margin-top:0; font-size:18px;">AI-Generated Chart Plan</h3>
{plans_html}
  </div>
</div>"""

def create_instructions_html(total_prompts: int = 50) -> str:
    """Create instructions HTML"""
    return f"""<div style="font-family: Arial, sans-serif; margin: 24px auto; line-height: 1.6;">

  <div style="background:#e8f4fd; border:1px solid #b6d4fe; border-radius:12px; padding:24px; margin-bottom:24px; box-shadow:0 2px 6px rgba(0,0,0,0.06);">
    <h2 style="color:#0b6fa4; margin:0 0 12px; font-size:22px;">Instructions</h2>
    <p style="margin:8px 0; font-size:16px; color:#333;">
      Below are <b>{total_prompts} vague prompts</b> that we collected from real user inquiries.  
      For each prompt, you will also see the <b>chart plan generated by a large language model (LLM)</b>.  
      These charts are based on a dataset that can support the suggested visualizations.
    </p>
    <p style="margin:12px 0; font-size:16px; color:#333;">
      Your job is to <b>rate whether you agree with the LLM's output plan</b>.  
      Please be <b>generous in your judgment</b> — the plan does not need to be perfect.  
      As long as the suggested charts are <b>reasonable and relevant</b> to the vague prompt, you may consider them acceptable.
    </p>
    <p style="margin:12px 0 0; font-size:16px; font-weight:bold; color:#444;">
      You will rate each plan on:
    </p>
    <ul style="margin:8px 0 0 20px; padding:0; color:#333; font-size:15px;">
      <li><b>Does the generated chart plan match the intent of the vague prompt?</b> (1 = Not at all, 7 = Completely)</li>
      <li><b>Does the generated chart plan have the potential to support further exploration?</b> (1 = Not at all, 7 = Definitely)</li>
    </ul>
  </div>

</div>"""

class ChartEvaluationSurveyBuilder:
    """Specialized builder for chart evaluation surveys"""
    
    def __init__(self, survey_name: str = "Chart Plan Evaluation"):
        self.builder = QSFBuilder()
        self.builder.survey_data["SurveyEntry"]["SurveyName"] = survey_name
        self.created_blocks = {}
        
    def add_consent_form(self, custom_html: str = None) -> str:
        """Add consent form to survey"""
        if custom_html is None:
            # Use a simplified consent form
            custom_html = """<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 24px auto; line-height: 1.6;">
  <div style="background:#f9fbfd; border:1px solid #d0d7de; border-radius:12px; padding:20px; margin-bottom:20px;">
    <h1 style="color:#0b6fa4; margin:0 0 8px;">Consent Form</h1>
    <p><b>Study:</b> Chart Plan Evaluation</p>
    <p>By clicking "I consent" below, you agree to participate in this evaluation study.</p>
  </div>
</div>"""
        
        consent_qid = self.builder.create_multiple_choice_question(
            custom_html,
            ["I consent", "I do not consent"],
            data_export_tag="consent"
        )
        
        # Create consent block
        consent_block = self.builder.create_new_block("Consent", "Consent Form")
        self.builder.add_to_block(consent_block, [consent_qid])
        self.created_blocks["consent"] = consent_block
        
        return consent_qid
    
    def add_instructions(self, total_prompts: int = 50) -> str:
        """Add instructions to survey"""
        instructions_html = create_instructions_html(total_prompts)
        instructions_qid = self.builder.create_display_question(
            instructions_html, 
            "instructions"
        )
        return instructions_qid
    
    def add_prompt_evaluation_set(self, 
                                prompts_data: List[Dict], 
                                set_name: str = "Set A") -> List[str]:
        """Add a set of prompt evaluations"""
        
        # Create block for this set
        set_block = self.builder.create_new_block(
            set_name, 
            f"Evaluation questions for {set_name}"
        )
        
        created_qids = []
        
        for i, prompt_data in enumerate(prompts_data, 1):
            # Create the evaluation question
            prompt_html = create_vague_prompt_html(prompt_data["prompt"])
            charts_html = create_chart_plans_html(prompt_data["plans"])
            full_html = prompt_html + charts_html
            
            eval_qid = self.builder.create_likert_matrix_question(
                full_html,
                CHART_EVALUATION_TEMPLATE["choices"],
                CHART_EVALUATION_TEMPLATE["scale_labels"],
                data_export_tag=f"A-{i}",
                required=True
            )
            
            # Create optional feedback question
            feedback_qid = self.builder.create_text_entry_question(
                "(Optional)&nbsp;Please explain your rating",
                data_export_tag=f"A-{i}f",
                required=False
            )
            
            created_qids.extend([eval_qid, feedback_qid])
            
            # Add page break after every few questions for better UX
            if i % 5 == 0 and i < len(prompts_data):
                # Add page break to block elements
                pass  # Page breaks are handled in block elements
        
        # Add all questions to the block
        self.builder.add_to_block(set_block, created_qids)
        self.created_blocks[set_name.lower().replace(" ", "_")] = set_block
        
        return created_qids
    
    def save_survey(self, output_file: str):
        """Save the complete survey"""
        self.builder.save_qsf(output_file)

# Example usage functions
def load_prompts_from_json(file_path: str) -> List[Dict]:
    """Load prompts and chart plans from JSON file"""
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def create_sample_prompts_data() -> List[Dict]:
    """Create sample prompts data for testing"""
    return [
        {
            "prompt": "Certain regions are reportedly safer than others.",
            "plans": [
                {
                    "title": "Safety Score by Region",
                    "type": "Bar chart",
                    "description": "The 'Safety Score by Region' bar chart reveals how different regions rank in terms of safety, with North America, Europe, and Asia each having distinct safety scores."
                },
                {
                    "title": "Safety vs Popularity",
                    "type": "Bubble chart", 
                    "description": "The 'Safety vs Popularity' scatter plot shows the relationship between safety scores and popularity scores for different regions."
                }
            ]
        },
        {
            "prompt": "Africa continues to draw a lot of attention.",
            "plans": [
                {
                    "title": "Popularity of Africa Over Time",
                    "type": "Line chart",
                    "description": "Shows how interest in visiting Africa has grown over the years, suggesting an increasing appeal of the continent for tourists."
                },
                {
                    "title": "Comparative Popularity of Regions", 
                    "type": "Bar chart",
                    "description": "Contrasts Africa's appeal with Asia and Europe, providing understanding of how Africa's tourism performance stacks up."
                }
            ]
        }
    ]

def example_create_survey():
    """Example: Create a complete survey"""
    
    # Create survey builder
    survey = ChartEvaluationSurveyBuilder("Chart Plan Evaluation - Example")
    
    # Add consent form
    survey.add_consent_form()
    
    # Add instructions  
    survey.add_instructions(total_prompts=2)
    
    # Add sample evaluation questions
    sample_data = create_sample_prompts_data()
    survey.add_prompt_evaluation_set(sample_data, "Sample Set")
    
    # Save survey
    output_file = "/Users/h2o/Documents/Projects/Research/Visplora/data/example-chart-evaluation.qsf"
    survey.save_survey(output_file)
    print(f"Example survey created: {output_file}")

if __name__ == "__main__":
    # Create example survey
    example_create_survey()